/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkinsDocker;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import jenkinsDocker.entity.ThemeParkRide;
import jenkinsDocker.repository.ThemeParkRideRepository;

@SpringBootApplication
public class App {
    
    public static void main(String[] args) {
    	SpringApplication.run(App.class);
    }
    
    @Bean
    public CommandLineRunner sampleData(ThemeParkRideRepository repository) {
    	return (args) -> {
    		repository.save(new ThemeParkRide("Ride","Coaster",1,1));
    		repository.save(new ThemeParkRide("Ride 2","Segunda 2",2,5));
    		repository.save(new ThemeParkRide("Ride 3","Segunda 3",3,6));
    		
    		
    	};
    }
}
